DELETE DATABASE IF EXISTS bd_stripe_maps;
CREATE DATABASE IF NOT EXISTS bd_stripe_maps;

USE bd_stripe_maps;

CREATE TABLE USERS(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	token VARCHAR(255) NOT NULL,
	rol ENUM('Client', 'Admin', 'Shipper') NOT NULL,
	address LONGTEXT NOT NULL,
	longitud BIGINT,
	latitud BIGINT,
	CONSTRAINT userPK PRIMARY KEY(id)
);

CREATE TABLE ORDERS(
	id INT NOT NULL AUTO_INCREMENT,
	user_id INT NOT NULL,
	shipper_id INT NOT NULL,
	total_price DECIMAL(10, 2) NOT NULL,
	order_state ENUM('Pendant', 'In Delivery', 'Cancelled') NOT NULL DEFAULT 'Pendant',
	CONSTRAINT orderPK PRIMARY KEY(id),
	CONSTRAINT userFK FOREIGN KEY(user_id) REFERENCES USERS(id),
	CONSTRAINT shipperFK FOREIGN KEY(shipper_id) REFERENCES USERS(id)
);

CREATE TABLE PRODUCTS(
	id INT NOT NULL AUTO_INCREMENT,
	product_name VARCHAR(255) NOT NULL,
	product_description VARCHAR(255) NOT NULL,
	product_price DECIMAL(10, 2) NOT NULL,
	CONSTRAINT productPK PRIMARY KEY(id)
);

CREATE TABLE ORDER_DETAILS(
	id INT NOT NULL AUTO_INCREMENT,
	order_id INT NOT NULL,
	product_id INT NOT NULL,
	product_quantity INT NOT NULL,
	subtotal_price DECIMAL(10, 2),
	CONSTRAINT orderdetailPK PRIMARY KEY(id),
	CONSTRAINT productFK FOREIGN KEY(product_id) REFERENCES PRODUCTS(id)
);

CREATE TABLE PAYMENTS(
	id INT NOT NULL AUTO_INCREMENT,
	order_id INT NOT NULL,
	payment_date DATETIME NOT NULL,
	total_payment DECIMAL(10, 2),
	CONSTRAINT paymentPK PRIMARY KEY(id),
	CONSTRAINT orderpayFK FOREIGN KEY(order_id) REFERENCES ORDERS(id)
);

ALTER TABLE USERS ADD COLUMN createdAt TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE USERS ADD COLUMN updateddAt TIMESTAMP NOT NULL DEFAULT NOW();

ALTER TABLE PRODUCTS ADD COLUMN createdAt TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE PRODUCTS ADD COLUMN updateddAt TIMESTAMP NOT NULL DEFAULT NOW();

ALTER TABLE PAYMENTS ADD COLUMN createdAt TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE PAYMENTS ADD COLUMN updateddAt TIMESTAMP NOT NULL DEFAULT NOW();

ALTER TABLE ORDERS ADD COLUMN createdAt TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE ORDERS ADD COLUMN updateddAt TIMESTAMP NOT NULL DEFAULT NOW();

ALTER TABLE ORDER_DETAILS ADD COLUMN createdAt TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE ORDER_DETAILS ADD COLUMN updateddAt TIMESTAMP NOT NULL DEFAULT NOW();

ALTER TABLE PAYMENTS ADD COLUMN user_id INT NOT NULL;